#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""Convenience wrapper for running clearmkvcnames directly from source tree."""


from pyPlexUtils.pyPlexUtils import clear_mkvchptnames


if __name__ == '__main__':
    clear_mkvchptnames()